---
- name: Learning how to use git
  hosts: planetexpress
  connection: ssh
  gather_facts: false

  tasks:
  - name: "Create a git archive from a repository"
    git:
      repo: https://github.com/ansible/ansible-examples.git
      dest: ~/ansibile_examples/
      archive: /tmp/ansible-examples.zip
