---
- name: Learning about blocks
  hosts: planetexpress
  connection: ssh
  gather_facts: false

  tasks:
  - name: BLOCK - This is what we want to TRY to do
    block:

      - name: Example task
        shell: "echo 'My single task ran' > example.txt"

      - name: Example task
        shell: "echo 'My second task ran' >> example.txt"

      - name: Example task
        shell: "echo 'My third task ran' >> example.txt"

    rescue:
      - name: Rescue task
        shell: "echo 'My rescue code ran. Maybe it undoes whatever the block tried to do' >> example.txt"

    always:
      - name: Always task
        shell: "echo 'This always runs. Maybe it is a commit, or an entry in a log' >> example.txt"
