---
- name: Copying files from controller to hosts
  hosts: planetexpress
  connection: ssh
  gather_facts: true

  tasks:
    - name: Copy Fry's resume to hosts
      copy:
        src: ~/mycode/files/fry.txt
        dest: ~/fry.txt
