---
- name: Copying content from controller to hosts
  hosts: planetexpress:!farnsworth
  connection: ssh
  gather_facts: true

  tasks:
  - name: Create the new group for ipv4 access
    group:
      name: sysadmin
      state: present
    become: true

  - name: Create a sysadmin user for ipv4 access
    user:
      name: admin1
      comment: "Example Admin"
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      group: sysadmin
    become: true

  - name: Copy gather fact var data into hosts
    copy:
      content: "{{ ansible_all_ipv4_addresses }}"
      dest: /home/admin1/ipv4info.txt
      backup: yes
      force: yes
      owner: admin1
      group: sysadmin
      mode: '0644'
    become: true
