---
- name: Working with simple dictionaries
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Loop across complex data structures
    debug:
      msg: "{{ item.name }} belongs in the {{ item.groups }} aisle"
    loop:
      - { name: 'orange', groups: 'fruit' }
      - { name: 'lemon', groups: 'fruit' }
      - { name: 'cookie', groups: 'snacks' }
      - { name: 'carrot', groups: 'vegetable' }
