---
- name: A playbook showing the file module
  hosts: planetexpress

  tasks:
  - name: Create directory where Space Station documents will reside
    become_user: root
    become: true
    file:
      path: "/home/{{ ansible_user }}/station_docs/"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: "0755"

  - name: "Create directory where Space Station documents will reside"
    copy:
      dest: "/home/{{ ansible_user }}/station_docs/navdata-{{ ansible_date_time.date }}.txt"
      content: "Earth\nMars\nSaturn\nEuropa"
