---
- name: Apache server installed
  hosts: web
  gather_facts: false
  become: true

  tasks:
  - name: Latest Apache version installed
    package:
      name: apache2
      state: latest

  - name: Apache enabled and running
    service:
      name: apache2
      enabled: true
      state: started

  - name: copy index.html
    copy:
      src: ~/mycode/files/index.html
      dest: /var/www/html/

  - name: Download a copy of apache2.conf
    get_url:
      url: https://raw.githubusercontent.com/rzfeeser/alta3files/master/apache2.conf
      dest: /etc/apache2/
    notify:
      - restart_apache

  handlers:
  - name: restart_apache
    service:
      name: apache2
      state: restarted
