---
- name: Debug playbook to display ansible facts
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Install an app with apt only on Ubuntu systems
      package:
        state: present
        name: sl
      when: ansible_distribution == "Ubuntu"
      become: true

    - name: Print out both users distro
      debug:
        var: ansible_distribution

    - name: Print out both users distro ver
      debug:
        var: ansible_distribution_version
