---
- name: Using the arista_backup role we created
  hosts: all
  connection: network_cli
  gather_facts: true

  vars:
    ansible_network_os: eos

  vars_files:
    - ~/switch.creds

  roles:
    - arista_backup

  tasks:
    - name: print to the screen
      debug:
        msg: "the roles section will run before any tasks"
