---
- name: How to prompt for variables
  hosts: localhost
  gather_facts: false

  vars_prompt:
  - name: "yourpassword"
    prompt: "What is your password?"
    private: true
    encrypt: "sha512_crypt"
    confirm: true
    salt_size: 7
    default: "qwerty"

  tasks:
  - name: Print out the password
    debug:
      msg: "{{ yourpassword }}"
