---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: false
  connection: ssh

  vars:
    ship_name: Bessie
    ship_type: Intergalactic
    engines: Dark Matter
    dark_matter_balls: 63
    backup_engines: Chemical


  tasks:
  - name: configure spaceship registration
    template:
      src: templates/ship.cfg.j2
      dest: ~/ship.cfg
